### ISSUE TITLE
Problem with Chinese data

### ISSUE THREAD

**Issue by geekboood** [YuukanOO/tracy#2]
Hi! When I try to use this awesome tool to annotate Chinese datasets, I face a problem that the range of entities will cross over with each other if two entities is adjacent as you can see in the image. 
![issue](https://user-images.githubusercontent.com/23272969/56094362-354a1200-5f06-11e9-8142-92b549db1413.png)
The raw text is `把卧室的灯打开` and `卧室` means bedroom, `灯` means lamp, `打开` means turn on. The whole sentence means "turn on the lamp in the bedroom". 
Also when I try to export the data to a JSON file these entities are totally a mess. 
May be the reason for the problem is that there is a space between words in English but not in Chinese.

**Comment by YuukanOO** [comment]
The problem appears in other languages too when two entities are adjacent as you said. I'll try to have a look and fix this.

**Comment by YuukanOO** [comment]
I just pushed a fix with 09e84ac. Can you confirm it works as expected using the [github page](https://yuukanoo.github.io/tracy/)?

For your second issue, can you provide some examples?

**Comment by geekboood** [comment]
@YuukanOO I can confirm that it is fixed! Thank you! And I believe the second issue is related to the first one and they are all fixed now!
